export default {
  extends: '@tenphi/tasty',

  tokens: [
    // -- Base palette --
    '#base-black',
    '#base-white',

    // -- Primary palette --
    '#primary-surface',
    '#primary-surface-2',
    '#primary-surface-3',
    '#primary-text',
    '#primary-text-2',
    '#primary-text-3',
    '#primary-text-soft',
    '#primary-text-soft-2',
    '#primary-text-soft-3',
    '#primary-border',
    '#primary-accent-surface-text',
    '#primary-accent-surface',
    '#primary-accent-text',
    '#primary-accent-text-2',
    '#primary-accent-text-3',
    '#primary-icon',
    '#primary-disabled',
    '#primary-shadow-border',
    '#primary-shadow-logo',
    '#primary-shadow-sm',
    '#primary-shadow-md',
    '#primary-shadow-lg',
    '#primary-overlay',
    '#primary-accent-surface-2',
    '#primary-accent-surface-3',

    // -- Violet palette --
    '#violet-surface',
    '#violet-surface-2',
    '#violet-surface-3',
    '#violet-text',
    '#violet-text-2',
    '#violet-text-3',
    '#violet-text-soft',
    '#violet-text-soft-2',
    '#violet-text-soft-3',
    '#violet-border',
    '#violet-accent-surface-text',
    '#violet-accent-surface',
    '#violet-accent-text',
    '#violet-accent-text-2',
    '#violet-accent-text-3',
    '#violet-icon',
    '#violet-disabled',
    '#violet-shadow-border',
    '#violet-shadow-logo',
    '#violet-shadow-sm',
    '#violet-shadow-md',
    '#violet-shadow-lg',
    '#violet-overlay',

    // -- Coral palette --
    '#coral-surface',
    '#coral-surface-2',
    '#coral-surface-3',
    '#coral-text',
    '#coral-text-2',
    '#coral-text-3',
    '#coral-text-soft',
    '#coral-text-soft-2',
    '#coral-text-soft-3',
    '#coral-border',
    '#coral-accent-surface-text',
    '#coral-accent-surface',
    '#coral-accent-text',
    '#coral-accent-text-2',
    '#coral-accent-text-3',
    '#coral-icon',
    '#coral-disabled',
    '#coral-shadow-border',
    '#coral-shadow-logo',
    '#coral-shadow-sm',
    '#coral-shadow-md',
    '#coral-shadow-lg',
    '#coral-overlay',

    // -- Teal palette --
    '#teal-surface',
    '#teal-surface-2',
    '#teal-surface-3',
    '#teal-text',
    '#teal-text-2',
    '#teal-text-3',
    '#teal-text-soft',
    '#teal-text-soft-2',
    '#teal-text-soft-3',
    '#teal-border',
    '#teal-accent-surface-text',
    '#teal-accent-surface',
    '#teal-accent-text',
    '#teal-accent-text-2',
    '#teal-accent-text-3',
    '#teal-icon',
    '#teal-disabled',
    '#teal-shadow-border',
    '#teal-shadow-logo',
    '#teal-shadow-sm',
    '#teal-shadow-md',
    '#teal-shadow-lg',
    '#teal-overlay',

    // -- Amber palette --
    '#amber-surface',
    '#amber-surface-2',
    '#amber-surface-3',
    '#amber-text',
    '#amber-text-2',
    '#amber-text-3',
    '#amber-text-soft',
    '#amber-text-soft-2',
    '#amber-text-soft-3',
    '#amber-border',
    '#amber-accent-surface-text',
    '#amber-accent-surface',
    '#amber-accent-text',
    '#amber-accent-text-2',
    '#amber-accent-text-3',
    '#amber-icon',
    '#amber-disabled',
    '#amber-shadow-border',
    '#amber-shadow-logo',
    '#amber-shadow-sm',
    '#amber-shadow-md',
    '#amber-shadow-lg',
    '#amber-overlay',

    // -- Blue palette --
    '#blue-surface',
    '#blue-surface-2',
    '#blue-surface-3',
    '#blue-text',
    '#blue-text-2',
    '#blue-text-3',
    '#blue-text-soft',
    '#blue-text-soft-2',
    '#blue-text-soft-3',
    '#blue-border',
    '#blue-accent-surface-text',
    '#blue-accent-surface',
    '#blue-accent-text',
    '#blue-accent-text-2',
    '#blue-accent-text-3',
    '#blue-icon',
    '#blue-disabled',
    '#blue-shadow-border',
    '#blue-shadow-logo',
    '#blue-shadow-sm',
    '#blue-shadow-md',
    '#blue-shadow-lg',
    '#blue-overlay',

    // -- Rose palette --
    '#rose-surface',
    '#rose-surface-2',
    '#rose-surface-3',
    '#rose-text',
    '#rose-text-2',
    '#rose-text-3',
    '#rose-text-soft',
    '#rose-text-soft-2',
    '#rose-text-soft-3',
    '#rose-border',
    '#rose-accent-surface-text',
    '#rose-accent-surface',
    '#rose-accent-text',
    '#rose-accent-text-2',
    '#rose-accent-text-3',
    '#rose-icon',
    '#rose-disabled',
    '#rose-shadow-border',
    '#rose-shadow-logo',
    '#rose-shadow-sm',
    '#rose-shadow-md',
    '#rose-shadow-lg',
    '#rose-overlay',

    // -- Lime palette --
    '#lime-surface',
    '#lime-surface-2',
    '#lime-surface-3',
    '#lime-text',
    '#lime-text-2',
    '#lime-text-3',
    '#lime-text-soft',
    '#lime-text-soft-2',
    '#lime-text-soft-3',
    '#lime-border',
    '#lime-accent-surface-text',
    '#lime-accent-surface',
    '#lime-accent-text',
    '#lime-accent-text-2',
    '#lime-accent-text-3',
    '#lime-icon',
    '#lime-disabled',
    '#lime-shadow-border',
    '#lime-shadow-logo',
    '#lime-shadow-sm',
    '#lime-shadow-md',
    '#lime-shadow-lg',
    '#lime-overlay',

    // -- Syntax palette (contrast-aware code highlighting) --
    '#syntax-text',
    '#syntax-bg',
    '#syntax-comment',
    '#syntax-punctuation',
    '#syntax-keyword',
    '#syntax-string',
    '#syntax-token',
    '#syntax-property',
    '#syntax-number',
    '#syntax-function',
    '#syntax-value',
    '#syntax-operator',

    // -- Locally-defined color tokens --
    '#border',
    '#tint-fill',
    '#tint-accent',
    '#tint-accent-3',

    // -- Project custom properties --
    '$card-radius',
    '$content-width',
    '$header-height',
    '$default-font-size',
    '$default-line-height',
    '$default-letter-spacing',
    '$default-font-weight',
    '$default-font-style',
    '$t2-line-height',
  ],

  states: [
    '@mobile',
    '@tablet',
    '@desktop',
    '@dark',
    '@high-contrast',
    '@reduce-motion',
  ],

  presets: ['d1', 'h1', 'h2', 'h3', 'h4', 'h5', 't1', 't2', 't3', 't4', 'strong'],

  recipes: ['palette', 'typography'],

  funcs: ['okhsl'],

  styles: ['scrollPaddingTop', 'textSizeAdjust'],
};
