import {
  tasty,
  BASE_STYLES,
  OUTER_STYLES,
  BLOCK_STYLES,
  COLOR_STYLES,
} from '@tenphi/tasty';

const Card = tasty({
  styles: {
    display: 'flex',
    flow: 'column',
    gap: '2x',
    padding: {
      '': '3x',
      '@mobile': '2x',
    },
    radius: '1cr',
    fill: '#tint-surface',
    border: '1bw solid #tint-border',
    textDecoration: 'none',
    transition: 'shadow, translate',
    shadow: {
      '': 'none',
      ':hover': '0 1x 2x #tint-shadow',
    },
    translate: {
      '': '0 0',
      ':hover': '0 -3px',
    },
    Header: {
      $: '>',
      display: 'flex',
      flow: 'row',
      placeContent: 'space-between',
      placeItems: 'center',
    },
    Icon: {
      $: '>Header>',
      display: 'inline-flex',
      placeItems: 'center',
      placeContent: 'center',
      width: '48px',
      height: '48px',
      radius: '14px',
      fill: '#tint-surface-strong',
      color: '#tint-accent-strong',
    },
    Title: {
      $: '>Header>',
      preset: 'h4',
      color: '#tint-accent',
      margin: '0',
    },
    Description: {
      $: '>',
      preset: 't2',
      color: '#text-soft',
      margin: '0',
    },
  },
  variants: {
    lime: {
      '#tint-surface': '#lime-surface-2',
      '#tint-surface-strong': '#lime-surface-3',
      '#tint-border': '#lime-border',
      '#tint-accent': '#lime-accent-text-2',
      '#tint-accent-strong': '#lime-accent-text-3',
      '#tint-shadow': '#lime-shadow-sm',
    },
    coral: {
      '#tint-surface': '#coral-surface-2',
      '#tint-surface-strong': '#coral-surface-3',
      '#tint-border': '#coral-border',
      '#tint-accent': '#coral-accent-text-2',
      '#tint-accent-strong': '#coral-accent-text-3',
      '#tint-shadow': '#coral-shadow-sm',
    },
    teal: {
      '#tint-surface': '#teal-surface-2',
      '#tint-surface-strong': '#teal-surface-3',
      '#tint-border': '#teal-border',
      '#tint-accent': '#teal-accent-text-2',
      '#tint-accent-strong': '#teal-accent-text-3',
      '#tint-shadow': '#teal-shadow-sm',
    },
    amber: {
      '#tint-surface': '#amber-surface-2',
      '#tint-surface-strong': '#amber-surface-3',
      '#tint-border': '#amber-border',
      '#tint-accent': '#amber-accent-text-2',
      '#tint-accent-strong': '#amber-accent-text-3',
      '#tint-shadow': '#amber-shadow-sm',
    },
    violet: {
      '#tint-surface': '#violet-surface-2',
      '#tint-surface-strong': '#violet-surface-3',
      '#tint-border': '#violet-border',
      '#tint-accent': '#violet-accent-text-2',
      '#tint-accent-strong': '#violet-accent-text-3',
      '#tint-shadow': '#violet-shadow-sm',
    },
    rose: {
      '#tint-surface': '#rose-surface-2',
      '#tint-surface-strong': '#rose-surface-3',
      '#tint-border': '#rose-border',
      '#tint-accent': '#rose-accent-text-2',
      '#tint-accent-strong': '#rose-accent-text-3',
      '#tint-shadow': '#rose-shadow-sm',
    },
    blue: {
      '#tint-surface': '#blue-surface-2',
      '#tint-surface-strong': '#blue-surface-3',
      '#tint-border': '#blue-border',
      '#tint-accent': '#blue-accent-text-2',
      '#tint-accent-strong': '#blue-accent-text-3',
      '#tint-shadow': '#blue-shadow-sm',
    },
  },
  elements: { Header: 'div', Icon: 'span', Title: 'h3', Description: 'p' },
  styleProps: [
    ...BASE_STYLES,
    ...OUTER_STYLES,
    ...BLOCK_STYLES,
    ...COLOR_STYLES,
  ],
});

export default Card;
